name: search_field_dropdown
description: A customizable dropdown widget for Flutter with advanced styling, search functionality, and dynamic data handling.
homepage: https://github.com/sumit-home2904/search_field_dropdown/tree/main/example
repository: https://github.com/sumit-home2904/search_field_dropdown/
issue_tracker: https://github.com/sumit-home2904/search_field_dropdown/issues
Publisher: Sumit Sharma
license: MIT

version: 1.0.2

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
